// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MainnetJs from "mainnet-js";

var Types = {};

var CashTokens = {};

function init(param) {
  MainnetJs.DefaultProvider.servers.testnet = ["wss://chipnet.imaginary.cash:50004"];
  
}

init(undefined);

export {
  Types ,
  CashTokens ,
  init ,
  
}
/*  Not a pure module */
