// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var MainnetJs = require("mainnet-js");

var Types = {};

MainnetJs.TestNetWallet.newRandom().then(function (wallet) {
        return MainnetJs.TestNetWallet.watchOnly(wallet.address);
      }).then(function (watchOnlyWallet) {
      console.log(watchOnlyWallet);
      
    });

var Test = {};

exports.Types = Types;
exports.Test = Test;
/*  Not a pure module */
