// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MainnetJs from "mainnet-js";

var Types = {};

function initChipnet(param) {
  MainnetJs.DefaultProvider.servers.testnet = ["wss://chipnet.imaginary.cash:50004"];
  
}

export {
  Types ,
  initChipnet ,
  
}
/* mainnet-js Not a pure module */
