// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Promise from "@ryyppy/rescript-promise/src/Promise.mjs";

function sendError(response, statusCode, statusText) {
  return Promise.resolve(response.status(statusCode).send({
                  TAG: /* Error */1,
                  _0: statusText
                }));
}

function handleGatewayError(_request, response, e) {
  console.log(e);
  var match;
  if (e.RE_EXN_ID === $$Promise.JsError) {
    var response$1 = e._1.response;
    match = response$1 !== undefined ? [
        response$1.status,
        "Gateway responded: " + response$1.statusText
      ] : [
        502,
        "Gateway responded with an unparseable resonse"
      ];
  } else {
    match = [
      502,
      "Some unknown gateway error"
    ];
  }
  return sendError(response, match[0], match[1]);
}

export {
  sendError ,
  handleGatewayError ,
  
}
/* No side effect */
