// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Vercel = require("../../src/bindings/Vercel.bs.js");
var $$Promise = require("@ryyppy/rescript-promise/src/Promise.bs.js");
var MainnetJs = require("mainnet-js");

function $$default(request, response) {
  return $$Promise.$$catch(MainnetJs.TestNetWallet.newRandom().then(function (wallet) {
                  return Promise.resolve(response.status(200).send({
                                  TAG: /* Ok */0,
                                  _0: {
                                    mnemonic: wallet.mnemonic
                                  }
                                }));
                }), (function (param) {
                return Vercel.handleGatewayError(request, response, param);
              }));
}

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* mainnet-js Not a pure module */
