// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vercel from "../../src/bindings/Vercel.mjs";
import * as $$Promise from "@ryyppy/rescript-promise/src/Promise.mjs";
import * as MainnetJs from "mainnet-js";

function $$default(request, response) {
  return $$Promise.$$catch(MainnetJs.TestNetWallet.newRandom().then(function (wallet) {
                  return Promise.resolve(response.status(200).send({
                                  TAG: /* Ok */0,
                                  _0: {
                                    mnemonic: wallet.mnemonic
                                  }
                                }));
                }), (function (param) {
                return Vercel.handleGatewayError(request, response, param);
              }));
}

export {
  $$default ,
  $$default as default,
  
}
/* mainnet-js Not a pure module */
