// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Vercel = require("../../src/bindings/Vercel.bs.js");
var $$Promise = require("@ryyppy/rescript-promise/src/Promise.bs.js");
var MainnetJs = require("mainnet-js");

function $$default(request, response) {
  var seed = request.query.seed;
  if (seed !== undefined) {
    return $$Promise.$$catch(MainnetJs.TestNetWallet.fromSeed(seed).then(function (wallet) {
                    return Promise.resolve(response.status(200).send({
                                    TAG: /* Ok */0,
                                    _0: wallet.address
                                  }));
                  }), (function (param) {
                  return Vercel.handleGatewayError(request, response, param);
                }));
  } else {
    return Vercel.sendError(response, 400, "Invalid seed");
  }
}

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* mainnet-js Not a pure module */
