// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vercel from "../../src/bindings/Vercel.mjs";
import * as $$Promise from "@ryyppy/rescript-promise/src/Promise.mjs";
import * as MainnetJs from "mainnet-js";

function $$default(request, response) {
  var seed = request.query.seed;
  if (seed !== undefined) {
    return $$Promise.$$catch(MainnetJs.TestNetWallet.fromSeed(seed).then(function (wallet) {
                    return Promise.resolve(response.status(200).send({
                                    TAG: /* Ok */0,
                                    _0: {
                                      address: wallet.address
                                    }
                                  }));
                  }), (function (param) {
                  return Vercel.handleGatewayError(request, response, param);
                }));
  } else {
    return Vercel.sendError(response, 400, "Invalid seed");
  }
}

export {
  $$default ,
  $$default as default,
  
}
/* mainnet-js Not a pure module */
