// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Vercel = require("../../src/bindings/Vercel.bs.js");
var $$Promise = require("@ryyppy/rescript-promise/src/Promise.bs.js");
var MainnetJs = require("mainnet-js");

function $$default(request, response) {
  var address = request.query.address;
  if (address !== undefined) {
    return $$Promise.$$catch(MainnetJs.TestNetWallet.watchOnly(address).then(function (wallet) {
                      return wallet.getBalance();
                    }).then(function (balance) {
                    return Promise.resolve(response.status(200).send({
                                    TAG: /* Ok */0,
                                    _0: {
                                      balance: balance
                                    }
                                  }));
                  }), (function (param) {
                  return Vercel.handleGatewayError(request, response, param);
                }));
  } else {
    return Vercel.sendError(response, 400, "No Address provided");
  }
}

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* mainnet-js Not a pure module */
