// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vercel from "../../src/bindings/Vercel.mjs";
import * as $$Promise from "@ryyppy/rescript-promise/src/Promise.mjs";
import * as MainnetJs from "mainnet-js";

function $$default(request, response) {
  var match = request.query.address;
  var match$1 = request.query.tokenId;
  if (match !== undefined) {
    if (match$1 !== undefined) {
      return $$Promise.$$catch(MainnetJs.TestNetWallet.watchOnly(match).then(function (wallet) {
                        return wallet.getTokenBalance(match$1);
                      }).then(function (balance) {
                      return Promise.resolve(response.status(200).send({
                                      TAG: /* Ok */0,
                                      _0: {
                                        balance: balance
                                      }
                                    }));
                    }), (function (param) {
                    return Vercel.handleGatewayError(request, response, param);
                  }));
    } else {
      return MainnetJs.TestNetWallet.watchOnly(match).then(function (wallet) {
                    return wallet.getAllTokenBalances();
                  }).then(function (balance) {
                  return Promise.resolve(response.status(200).send({
                                  TAG: /* Ok */0,
                                  _0: {
                                    balance: balance
                                  }
                                }));
                });
    }
  } else {
    return Vercel.sendError(response, 400, "No address provided");
  }
}

export {
  $$default ,
  $$default as default,
  
}
/* mainnet-js Not a pure module */
