// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var MainLayout = require("./layouts/MainLayout.bs.js");
var Router = require("next/router");

function $$default(props) {
  var router = Router.useRouter();
  var content = React.createElement(props.Component, props.pageProps);
  var match = router.route;
  if (match === "/examples") {
    return React.createElement(MainLayout.make, {
                children: null
              }, React.createElement("h1", {
                    className: "font-bold"
                  }, "Examples Section"), React.createElement("div", undefined, content));
  } else {
    return React.createElement(MainLayout.make, {
                children: content
              });
  }
}

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
